{
 "title": "Diagnostic PetClinic",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP Response Time (P95)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(job)(\n    rate(http_server_requests_seconds_sum[1m])\n)\n/\nsum by(job)(\n    rate(http_server_requests_seconds_count[1m])\n)\n*1000",
     "legendFormat": "{{job}} {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(job)(\n    rate(http_server_requests_seconds_count{\n        uri!=\"/actuator/prometheus\",\n        uri!=\"/actuator/health\"\n    }[1m])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Log warn, error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(job)(\n  rate(logback_events_total{level=~\"warn|error\"}[1m])\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "process_cpu_usage * 100", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "jvm_memory_used_bytes", "legendFormat": "{{job}}" }
   ]
  }
 ]
}